FROM ubuntu:16.04

RUN apt-get update

RUN apt-get -y install default-jdk
RUN apt-get -y install maven

COPY logger/ /root/logger/
RUN mvn --file /root/logger/ clean install

CMD mvn --file /root/logger/ exec:java
